### ISSUE TITLE
Game title and greeting message is mixing up.

### ISSUE THREAD

**Issue by MitanshuPatel999** [open-source-bootcamp/CubeFlyer#4]
**Describe the bug**
No proper styling of homepage texts.

**To Reproduce**
1. On opening homepage

**Expected behavior**
There should be proper space between title and greeting message. Font-size should be varied automatically as per the screen sizes. 

**Screenshot**
![image](https://user-images.githubusercontent.com/95534153/236708981-36124efe-d797-4bfa-a9ef-a4b358515dd3.png)

**Comment by jimbobbennett** [comment]
This is a template repo designed for folks to use to create the repo for an event where contributors work on bugs, so closing this as this is the kind of bug we'd expect someone to find and fix during an event using the output of this template repo.
